version: "3.9"
services:
  signal:
    image: netbirdio/signal:${NETBIRD_SIGNAL_VERSION}
    labels:
      logging: "promtail"
      logging_job: "netbird-signal"
    volumes:
      - netbird-signal:/var/lib/netbird
    networks:
      opendutnet:
        ipv4_address: 192.168.32.210
        aliases:
          - netbird-signal

  management:
    build:
      context: ../../..
      dockerfile: ./.ci/docker/netbird/Dockerfile_management
      args:
        NETBIRD_MANAGEMENT_VERSION: ${NETBIRD_MANAGEMENT_VERSION}
    labels:
      logging: "promtail"
      logging_job: "netbird-management"
    volumes:
      - netbird-mgmt:/var/lib/netbird
      - ./management.json:/etc/netbird/management.json
      - "../../../resources/development/tls/insecure-development-ca.pem:/usr/local/share/ca-certificates/insecure-development-ca.crt:ro"
      - netbird-management-keys:/management
      - "../../../resources/development/tls/:/opendut-tls/:ro"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
      - KEYCLOAK_URL=https://keycloak.internal
      - NETBIRD_MANAGEMENT_URL=https://netbird-management
      # https://github.com/netbirdio/dashboard/blob/58cec8fcd16dbb8467761f5ed55d18bccbc18e5b/src/utils/helpers.ts#L71 requires domain with tld identifier; it does not work without a suffix
      - KEYCLOAK_REALM_URL=https://keycloak.internal/realms/netbird/.well-known/openid-configuration
      - NETBIRD_PASSWORD=netbird
    healthcheck:
      test: ["CMD", "/netbird-management-health.sh"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 90s
    networks:
      opendutnet:
        ipv4_address: 192.168.32.214
        aliases:
          - netbird-management-container

  # traefik performs tls offloading
  traefik:
    image: docker.io/traefik:v2.10.4
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Redirect to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--providers.docker=false"
      - "--log.level=DEBUG"
      - "--log.format=json"
      - "--accesslog"
      - "--accesslog.format=json"
    environment:
      - "LEGO_CA_CERTIFICATES=/opendut-tls/insecure-development-ca.pem"
    labels:
      logging: "promtail"
      logging_job: "netbird-traefik"
#    ports:
#      - "127.0.0.1:8082:8080"
#      - "80:80"
#      - "443:443"
    volumes:
      - ./traefik/:/etc/traefik/dynamic:ro
      - "../../../resources/development/tls/:/opendut-tls/:ro"
    networks:
      opendutnet:
        ipv4_address: 192.168.32.211
        aliases:
        - netbird-management
        - netbird-dashboard

  # TODO: can this init stuff moved to management itself?
  management_init:
    build:
      context: ../../..
      dockerfile: ./.ci/docker/netbird/Dockerfile_netbird_init
      args:
        - PUID=$PUID
        - PGID=$PGID
        - PUSER=$PUSER
        - PGROUP=$PGROUP
    user: $DOCKER_USER # ${UID}:${GID} run with user privileges
    labels:
      logging: "promtail"
      logging_job: "netbird-management-init"
    volumes:
      #- ./management/:/management
      - netbird-management-keys:/management
    # for fast update of provisioning the scripts are mounted as volumes
      - ./netbird-api-functions.sh:/netbird-api-functions.sh
      - ./netbird-api-init.sh:/netbird-api-init.sh
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123456
      - KEYCLOAK_URL=https://keycloak.internal
      - NETBIRD_MANAGEMENT_URL=https://netbird-management
      - KEYCLOAK_REALM_URL=https://keycloak.internal/realms/netbird/.well-known/openid-configuration
      - NETBIRD_PASSWORD=netbird
      # TODO: CLEANUP!
      - PUID
      - PGID
      - PUSER
      - PGROUP
    networks:
      opendutnet:
        aliases:
          - netbird-init

  coturn:
    # https://hub.docker.com/r/coturn/coturn/tags
    image: coturn/coturn:4.6.2
    hostname: netbird-coturn
    labels:
      logging: "promtail"
      logging_job: "netbird-coturn"
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
    command:
      - -c /etc/turnserver.conf
    networks:
      opendutnet:
        ipv4_address: 192.168.32.212
        aliases:
          - netbird-coturn

  dashboard:
    # https://hub.docker.com/r/netbirdio/dashboard/tags
    image: netbirdio/dashboard:${NETBIRD_DASHBOARD_VERSION}
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://netbird-management
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://netbird-management
      # OIDC
      - AUTH_AUDIENCE=netbird-client
      - AUTH_CLIENT_ID=netbird-client
      - AUTH_AUTHORITY=https://keycloak.internal/realms/netbird
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
    labels:
      logging: "promtail"
      logging_job: "netbird-dashboard"
    networks:
      opendutnet:
        ipv4_address: 192.168.32.213
        aliases:
          - netbird-dashboard-container

networks:
  opendutnet:
    name: opendut_network
    external: true  # Use a pre-existing network

volumes:
  netbird-signal:
  netbird-mgmt:
  netbird-management-keys:
