[package]
name = "restbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autosar-data = "0.9.0"
nix = "0.25.1"
tokio = { version = "1", features = ["full"] }
