name: homepage
on:
  workflow_dispatch:  # manual trigger
  push:
    branches: [
      "main",
      "development",
    ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
    paths-ignore:
      - ".ci/kubernetes/**"

env:
  RUST_BACKTRACE: 1

jobs:
  homepage:
    uses: ./.github/workflows/job-homepage.yaml
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      runs-on: "${{ vars.OPENDUT_GH_RUNNER_SMALL || '[\"ubuntu-latest\"]' }}"
